export { CaslModule } from './casl.module'
export { AbilityFactory } from './ability.factory'
export { PoliciesGuard } from './policies.guard'
export { CheckPolicies } from './check-policies.decorator'
export type { PolicyHandler } from './check-policies.decorator'
export { DepartmentHierarchyService } from './department-hierarchy.service'
export type { DepartmentScope } from './department-hierarchy.service'
export type { AppAbility, CaslUser, Action, AppSubjects } from './casl.types'
export { createAppAbility } from './casl.types'
