import {
  ConflictException,
  Injectable,
  Logger,
  NotFoundException,
  BadRequestException,
  ForbiddenException,
} from '@nestjs/common'
import { PrismaService } from '@prisma'
import {
  DocumentCreateRequest,
  DocumentUpdateRequest,
  DocumentDeleteRequest,
  DocumentRetrieveAllRequest,
  DocumentRetrieveOneRequest,
  DocumentRetrieveAllResponse,
  DocumentRetrieveOneResponse,
} from './interfaces'
import { DocumentStatus, WorkflowStatus } from '@prisma/client'
import { MinioService } from '@clients'
import {
  PdfConverterUtil,
  DocumentGeneratorUtil,
  DocumentNumberGenerator,
  removeWatermark,
  translateActionTypeToUzbek,
} from '@common'
import { WorkflowPermissionService } from '../wopi/workflow-permission.service'
import { AuditLogService } from '../audit-log/audit-log.service'
import { ROLE_NAMES } from '@constants'
import { AuditAction } from '../audit-log/interfaces/audit-log-enums'

@Injectable()
export class DocumentService {
  private readonly logger = new Logger(DocumentService.name)
  readonly #_prisma: PrismaService
  readonly #_minio: MinioService
  readonly #_workflowPermissionService: WorkflowPermissionService
  readonly #_auditLogService: AuditLogService

  constructor(
    prisma: PrismaService,
    minio: MinioService,
    workflowPermissionService: WorkflowPermissionService,
    auditLogService: AuditLogService,
  ) {
    this.#_prisma = prisma
    this.#_minio = minio
    this.#_workflowPermissionService = workflowPermissionService
    this.#_auditLogService = auditLogService
  }

  async documentRetrieveAll(
    payload: DocumentRetrieveAllRequest,
  ): Promise<DocumentRetrieveAllResponse> {
    const pageNumber = payload.pageNumber ? Number(payload.pageNumber) : 1
    const pageSize = payload.pageSize ? Number(payload.pageSize) : 10
    const skip = (pageNumber - 1) * pageSize
    const take = pageSize
    const search = payload.search ? payload.search : undefined

    const isAdmin =
      payload.roleName === ROLE_NAMES.ADMIN ||
      payload.roleName === ROLE_NAMES.SUPER_ADMIN

    const searchCondition = search
      ? [
          { title: { contains: search, mode: 'insensitive' as const } },
          {
            documentNumber: { contains: search, mode: 'insensitive' as const },
          },
          { description: { contains: search, mode: 'insensitive' as const } },
        ]
      : undefined

    // Non-admin foydalanuvchilar faqat:
    //  1) O'zi yaratgan hujjatlarni
    //  2) Workflow'da ishtirok etgan (step assignee) hujjatlarni ko'radi
    const userAccessFilter =
      !isAdmin && payload.userId
        ? {
            OR: [
              { createdById: payload.userId },
              {
                workflow: {
                  some: {
                    workflowSteps: {
                      some: {
                        assignedToUserId: payload.userId,
                        deletedAt: null,
                      },
                    },
                    deletedAt: null,
                  },
                },
              },
            ],
          }
        : {}

    const documentList = await this.#_prisma.document.findMany({
      where: {
        deletedAt: null,
        ...(searchCondition && { OR: searchCondition }),
        ...(payload.status && { status: payload.status }),
        ...(payload.documentTypeId && {
          documentTypeId: payload.documentTypeId,
        }),
        ...(payload.journalId && { journalId: payload.journalId }),
        ...(payload.templateId && { templateId: payload.templateId }),
        ...userAccessFilter,
      },
      select: {
        id: true,
        title: true,
        description: true,
        documentNumber: true,
        status: true,
        documentType: {
          select: {
            id: true,
            name: true,
          },
        },
        createdBy: {
          select: {
            id: true,
            fullname: true,
          },
        },
        updatedBy: {
          select: {
            id: true,
            fullname: true,
          },
        },
        pdfUrl: true,
        attachments: {
          where: { deletedAt: null },
          select: {
            id: true,
            fileName: true,
            fileSize: true,
            fileUrl: true,
            mimeType: true,
            isAutoGenerated: true,
            createdAt: true,
          },
          orderBy: { createdAt: 'desc' },
        },
        journal: {
          select: {
            id: true,
            name: true,
            prefix: true,
            format: true,
          },
        },
      },
      skip,
      take,
      orderBy: {
        createdAt: 'desc',
      },
    })

    const count = await this.#_prisma.document.count({
      where: {
        deletedAt: null,
        ...(searchCondition && { OR: searchCondition }),
        ...(payload.status && { status: payload.status }),
        ...(payload.documentTypeId && {
          documentTypeId: payload.documentTypeId,
        }),
        ...(payload.journalId && { journalId: payload.journalId }),
        ...(payload.templateId && { templateId: payload.templateId }),
        ...userAccessFilter,
      },
    })

    return {
      data: documentList,
      count: count,
      pageNumber,
      pageSize,
      pageCount: Math.ceil(count / pageSize),
    }
  }

  async documentRetrieveOne(
    payload: DocumentRetrieveOneRequest,
  ): Promise<DocumentRetrieveOneResponse> {
    const isAdmin =
      payload.roleName === ROLE_NAMES.ADMIN ||
      payload.roleName === ROLE_NAMES.SUPER_ADMIN

    const document = await this.#_prisma.document.findFirst({
      where: {
        id: payload.id,
        deletedAt: null,
        ...(!isAdmin &&
          payload.userId && {
            OR: [
              { createdById: payload.userId },
              {
                workflow: {
                  some: {
                    workflowSteps: {
                      some: {
                        assignedToUserId: payload.userId,
                        deletedAt: null,
                      },
                    },
                    deletedAt: null,
                  },
                },
              },
            ],
          }),
      },
      select: {
        id: true,
        title: true,
        description: true,
        documentNumber: true,
        status: true,
        documentType: {
          select: {
            id: true,
            name: true,
          },
        },
        journal: {
          select: {
            id: true,
            name: true,
            prefix: true,
            format: true,
          },
        },
        createdBy: {
          select: {
            id: true,
            fullname: true,
          },
        },
        updatedBy: {
          select: {
            id: true,
            fullname: true,
          },
        },
        pdfUrl: true,
        xfdfUrl: true,
        attachments: {
          where: { deletedAt: null },
          select: {
            id: true,
            fileName: true,
            fileUrl: true,
            fileSize: true,
            mimeType: true,
            isAutoGenerated: true,
            createdAt: true,
            updatedAt: true,
          },
          orderBy: { createdAt: 'desc' },
        },
        createdAt: true,
        updatedAt: true,
      },
    })

    if (!document) {
      throw new NotFoundException('Document not found')
    }

    // Frontend uchun aniq ko'rsatma: qaysi faylni ochish kerak va qanday rejimda
    const atts = (document as any).attachments || []
    const OFFICE_MIMES = [
      'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
      'application/msword',
      'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
      'application/vnd.ms-excel',
      'application/vnd.openxmlformats-officedocument.presentationml.presentation',
      'application/vnd.ms-powerpoint',
    ]
    const latestDocx =
      atts.find((a: any) => OFFICE_MIMES.includes(a.mimeType)) || null
    const latestPdf =
      atts.find((a: any) => a.mimeType === 'application/pdf') || null

    // Foydalanuvchi roli
    const isCreator = document.createdBy?.id === payload.userId
    const isPlatformAdmin =
      payload.roleName === ROLE_NAMES.SUPER_ADMIN ||
      payload.roleName === ROLE_NAMES.ADMIN

    // Mantiq:
    //  - DRAFT/REJECTED + creator/admin → DOCX edit (Collabora full edit)
    //  - PENDING/IN_REVIEW + workflow ishtirokchi → PDF + XFDF annotation
    //  - APPROVED/ARCHIVED yoki boshqalar → PDF read-only
    let primaryAttachment: any = null
    let displayMode: 'EDIT_DOCX' | 'ANNOTATE_PDF' | 'VIEW_PDF' | 'NONE' = 'NONE'
    let canEdit = false

    const status = document.status
    const isDraft = status === 'DRAFT' || status === 'REJECTED'
    const isWorkflowActive = status === 'PENDING' || status === 'IN_REVIEW'
    const isFinal = status === 'APPROVED' || status === 'ARCHIVED'

    if (isDraft && (isCreator || isPlatformAdmin) && latestDocx) {
      // Yaratuvchi DOCX'ni Collabora'da to'liq tahrirlay oladi
      primaryAttachment = latestDocx
      displayMode = 'EDIT_DOCX'
      canEdit = true
    } else if (isWorkflowActive && latestPdf) {
      // Workflow active — PDF'ni ochish (annotation user huquqiga bog'liq)
      primaryAttachment = latestPdf
      // canEdit'ni aniqlash uchun WOPI permission service kerak,
      // hozircha frontend WOPI token olganda CheckFileInfo'dan UserCanWrite'ni oladi
      displayMode = 'ANNOTATE_PDF'
      canEdit = false // frontend WOPI orqali aniqlaydi
    } else if (isFinal && latestPdf) {
      primaryAttachment = latestPdf
      displayMode = 'VIEW_PDF'
      canEdit = false
    } else if (latestPdf) {
      // Fallback: PDF mavjud bo'lsa view-only
      primaryAttachment = latestPdf
      displayMode = 'VIEW_PDF'
      canEdit = false
    } else if (latestDocx && (isCreator || isPlatformAdmin)) {
      // PDF hali yaratilmagan, lekin DOCX bor
      primaryAttachment = latestDocx
      displayMode = 'EDIT_DOCX'
      canEdit = true
    }

    return {
      ...document,
      // Eski API uyumi: attachments PDFni qaytaradi, lekin DOCX ham mavjud (frontend kerak bo'lsa)
      attachments: latestPdf ? [latestPdf] : latestDocx ? [latestDocx] : [],
      // YANGI maydonlar — frontend shu asosida qaror qiladi
      primaryAttachment,
      displayMode,
      canEdit,
      hasDocx: !!latestDocx,
      hasPdf: !!latestPdf,
      docxAttachment: latestDocx,
      pdfAttachment: latestPdf,
    } as any
  }

  /**
   * Hujjat to'liq tarixi:
   * - Barcha fayl versiyalari (eski va yangi)
   * - Workflow bosqichlari va ulardagi harakatlar
   * - Audit log
   * - Status o'zgarishlari
   */
  async documentHistory(payload: {
    id: string
    userId: string
    roleName?: string
  }): Promise<any> {
    const document = await this.#_prisma.document.findFirst({
      where: { id: payload.id, deletedAt: null },
      include: {
        documentType: { select: { id: true, name: true } },
        journal: { select: { id: true, name: true, prefix: true } },
        createdBy: {
          select: { id: true, fullname: true, username: true, avatarUrl: true },
        },
        updatedBy: { select: { id: true, fullname: true, username: true } },
      },
    })

    if (!document) {
      throw new NotFoundException('Hujjat topilmadi')
    }

    // Permission check
    const isAdmin =
      payload.roleName === ROLE_NAMES.SUPER_ADMIN ||
      payload.roleName === ROLE_NAMES.ADMIN
    if (!isAdmin && document.createdById !== payload.userId) {
      // Workflow step'ga tayinlanganmi tekshirish
      const hasAccess = await this.#_prisma.workflowStep.findFirst({
        where: {
          assignedToUserId: payload.userId,
          workflow: { documentId: payload.id, deletedAt: null },
          deletedAt: null,
        },
      })
      if (!hasAccess) {
        throw new ForbiddenException(
          "Bu hujjat tarixini ko'rish huquqingiz yo'q",
        )
      }
    }

    // 1. Barcha fayl versiyalari (DOCX + PDF + boshqa)
    const allAttachments = await this.#_prisma.attachment.findMany({
      where: { documentId: payload.id, deletedAt: null },
      orderBy: { createdAt: 'asc' },
      select: {
        id: true,
        fileName: true,
        fileUrl: true,
        fileSize: true,
        mimeType: true,
        isAutoGenerated: true,
        createdAt: true,
        uploadedBy: {
          select: { id: true, fullname: true, username: true, avatarUrl: true },
        },
      },
    })

    // Mime type bo'yicha guruhlash (versiyalar)
    const fileVersions: Record<string, any[]> = {}
    for (const att of allAttachments) {
      if (!fileVersions[att.mimeType]) fileVersions[att.mimeType] = []
      fileVersions[att.mimeType].push(att)
    }

    // 2. Workflow va barcha bosqichlar + harakatlari
    const workflows = await this.#_prisma.workflow.findMany({
      where: { documentId: payload.id, deletedAt: null },
      include: {
        workflowSteps: {
          where: { deletedAt: null },
          orderBy: { order: 'asc' },
          include: {
            assignedToUser: {
              select: {
                id: true,
                fullname: true,
                username: true,
                avatarUrl: true,
              },
            },
            actions: {
              orderBy: { createdAt: 'asc' },
              include: {
                performedBy: {
                  select: {
                    id: true,
                    fullname: true,
                    username: true,
                    avatarUrl: true,
                  },
                },
              },
            },
            attachments: {
              include: {
                attachment: {
                  select: {
                    id: true,
                    fileName: true,
                    fileUrl: true,
                    mimeType: true,
                  },
                },
                uploadedBy: { select: { id: true, fullname: true } },
              },
            },
          },
        },
      },
    })

    // 3. Audit log (barcha o'zgarishlar)
    const auditLogs = await this.#_prisma.auditLog.findMany({
      where: {
        entity: 'Document',
        entityId: payload.id,
        deletedAt: null,
      },
      orderBy: { performedAt: 'desc' },
      include: {
        performedBy: {
          select: { id: true, fullname: true, username: true, avatarUrl: true },
        },
      },
    })

    // 4. Timeline — barcha hodisalarni vaqt bo'yicha tartiblash
    const timeline: any[] = []

    // Hujjat yaratildi
    timeline.push({
      type: 'DOCUMENT_CREATED',
      timestamp: document.createdAt,
      actor: document.createdBy,
      title: 'Hujjat yaratildi',
      description: `"${document.title}" hujjati yaratildi`,
      meta: { documentNumber: document.documentNumber, status: 'DRAFT' },
    })

    // Fayl versiyalari
    for (const att of allAttachments) {
      timeline.push({
        type: 'FILE_UPLOADED',
        timestamp: att.createdAt,
        actor: att.uploadedBy,
        title: att.isAutoGenerated
          ? 'Avtomatik PDF yaratildi'
          : 'Fayl yuklandi',
        description: att.fileName,
        meta: {
          attachmentId: att.id,
          fileName: att.fileName,
          fileUrl: att.fileUrl,
          mimeType: att.mimeType,
          fileSize: att.fileSize,
        },
      })
    }

    // Workflow steplar va actionlar
    for (const wf of workflows) {
      timeline.push({
        type: 'WORKFLOW_STARTED',
        timestamp: wf.createdAt,
        actor: document.createdBy,
        title: 'Ish jarayoni boshlandi',
        description: `${wf.type === 'CONSECUTIVE' ? 'Ketma-ket' : 'Parallel'} ish jarayoni`,
        meta: { workflowId: wf.id, type: wf.type, status: wf.status },
      })

      for (const step of wf.workflowSteps) {
        if (step.isCreator) continue

        if (step.startedAt) {
          timeline.push({
            type: 'STEP_STARTED',
            timestamp: step.startedAt,
            actor: step.assignedToUser,
            title: `${step.order}-bosqich boshlandi: ${translateActionTypeToUzbek(step.actionType)}`,
            description: `${step.assignedToUser?.fullname || ''} ga tayinlandi`,
            meta: {
              stepId: step.id,
              order: step.order,
              actionType: step.actionType,
              dueDate: step.dueDate,
            },
          })
        }

        for (const action of step.actions) {
          timeline.push({
            type: `STEP_${action.actionType}`,
            timestamp: action.createdAt,
            actor: action.performedBy,
            title: this.getActionTitle(
              action.actionType,
              step.order,
              step.actionType,
            ),
            description: action.comment || '',
            meta: {
              stepId: step.id,
              actionType: action.actionType,
              comment: action.comment,
            },
          })
        }

        if (step.isRejected && step.rejectedAt) {
          timeline.push({
            type: 'STEP_REJECTED',
            timestamp: step.rejectedAt,
            actor: step.assignedToUser,
            title: `${step.order}-bosqich rad etildi`,
            description: step.rejectionReason || '',
            meta: { stepId: step.id, reason: step.rejectionReason },
          })
        }

        if (step.completedAt && !step.isRejected) {
          timeline.push({
            type: 'STEP_COMPLETED',
            timestamp: step.completedAt,
            actor: step.assignedToUser,
            title: `${step.order}-bosqich yakunlandi: ${translateActionTypeToUzbek(step.actionType)}`,
            description: `${step.assignedToUser?.fullname || ''} muvaffaqiyatli bajardi`,
            meta: {
              stepId: step.id,
              order: step.order,
              actionType: step.actionType,
            },
          })
        }
      }
    }

    // Audit log yozuvlari
    for (const log of auditLogs) {
      timeline.push({
        type: `AUDIT_${log.action}`,
        timestamp: log.performedAt,
        actor: log.performedBy,
        title: this.getAuditTitle(log.action),
        description: '',
        meta: {
          changes: log.changes,
          oldValues: log.oldValues,
          newValues: log.newValues,
          ipAddress: log.ipAddress,
        },
      })
    }

    // Vaqt bo'yicha tartiblash (eski → yangi)
    timeline.sort(
      (a, b) =>
        new Date(a.timestamp).getTime() - new Date(b.timestamp).getTime(),
    )

    return {
      document: {
        id: document.id,
        title: document.title,
        documentNumber: document.documentNumber,
        status: document.status,
        documentType: document.documentType,
        journal: document.journal,
        createdBy: document.createdBy,
        updatedBy: document.updatedBy,
        createdAt: document.createdAt,
        updatedAt: document.updatedAt,
      },
      summary: {
        totalVersions: allAttachments.length,
        totalSteps: workflows.reduce(
          (sum, wf) =>
            sum + wf.workflowSteps.filter((s) => !s.isCreator).length,
          0,
        ),
        totalActions: workflows.reduce(
          (sum, wf) =>
            sum +
            wf.workflowSteps.reduce((s, step) => s + step.actions.length, 0),
          0,
        ),
        currentStatus: document.status,
        workflowsCount: workflows.length,
      },
      fileVersions,
      workflows,
      auditLogs,
      timeline,
    }
  }

  private getActionTitle(
    actionType: string,
    stepOrder: number,
    stepActionType: string,
  ): string {
    const stepActionUz = translateActionTypeToUzbek(stepActionType)
    const map: Record<string, string> = {
      STARTED: `${stepOrder}-bosqich boshlandi: ${stepActionUz}`,
      APPROVED: `${stepOrder}-bosqich tasdiqlandi: ${stepActionUz}`,
      REJECTED: `${stepOrder}-bosqich rad etildi: ${stepActionUz}`,
      REASSIGNED: `${stepOrder}-bosqich qayta tayinlandi`,
      COMMENTED: `${stepOrder}-bosqichga izoh qoldirildi`,
      DELEGATED: `${stepOrder}-bosqich boshqaga uzatildi`,
    }
    return map[actionType] || `${stepOrder}-bosqich: ${actionType}`
  }

  private getAuditTitle(action: string): string {
    const map: Record<string, string> = {
      CREATE: 'Hujjat yaratildi',
      UPDATE: "Hujjat ma'lumotlari yangilandi",
      DELETE: "Hujjat o'chirildi",
      RESTORE: 'Hujjat qayta tiklandi',
      APPROVE: 'Hujjat tasdiqlandi',
      REJECT: 'Hujjat rad etildi',
      ARCHIVE: 'Hujjat arxivlandi',
      OTHER: 'Boshqa amal',
    }
    return map[action] || action
  }

  async documentCreate(payload: DocumentCreateRequest): Promise<void> {
    const documentType = await this.#_prisma.documentType.findFirst({
      where: {
        id: payload.documentTypeId,
        deletedAt: null,
      },
    })

    if (!documentType) {
      throw new NotFoundException('Document type not found')
    }

    const journal = await this.#_prisma.journal.findFirst({
      where: {
        id: payload.journalId,
        deletedAt: null,
      },
      include: {
        department: true,
      },
    })

    if (!journal) {
      throw new NotFoundException('Journal not found')
    }

    // Fetch user with department and role information
    const user = await this.#_prisma.user.findFirst({
      where: {
        id: payload.userId,
        deletedAt: null,
      },
      select: {
        id: true,
        departmentId: true,
        role: {
          select: {
            name: true,
          },
        },
      },
    })

    if (!user) {
      throw new NotFoundException('User not found')
    }

    // Validate user can create document with this journal
    // Super Admin can create documents with any journal
    // Other users can only create documents with journals from their own department
    const isSuperAdmin = user.role?.name === ROLE_NAMES.SUPER_ADMIN

    if (journal.departmentId && !isSuperAdmin) {
      if (!user.departmentId) {
        throw new ForbiddenException(
          'You must be assigned to a department to create documents',
        )
      }

      if (user.departmentId !== journal.departmentId) {
        throw new ForbiddenException(
          'You can only create documents with journals from your own department',
        )
      }
    }

    // Auto-generate document number based on journal format
    const documentNumber = await DocumentNumberGenerator.generate(
      this.#_prisma,
      payload.journalId,
    )

    let templateId: string | undefined = payload.templateId || undefined
    let generatedAttachmentId: string | undefined = undefined

    if (payload.templateId && payload.tags) {
      const template = await this.#_prisma.documentTemplate.findFirst({
        where: {
          id: payload.templateId,
          deletedAt: null,
        },
        include: {
          templateFile: true,
        },
      })

      if (!template) {
        throw new NotFoundException('Document template not found')
      }

      if (template.requiredTags) {
        const validation = DocumentGeneratorUtil.validateTags(
          template.requiredTags as Record<string, any>,
          payload.tags,
        )

        if (!validation.valid) {
          throw new BadRequestException(
            `Missing required tags: ${validation.missing.join(', ')}`,
          )
        }
      }

      generatedAttachmentId = await this.generateDocumentFromTemplate(
        template,
        payload.tags,
        payload.userId,
      )
    } else if (payload.templateId && !payload.tags) {
      throw new BadRequestException('Tags are required when using a template')
    }

    this.logger.log(payload)

    const createdDocument = await this.#_prisma.document.create({
      data: {
        title: payload.title,
        description: payload.description,
        documentNumber: documentNumber,
        status: DocumentStatus.DRAFT,
        documentTypeId: payload.documentTypeId,
        journalId: payload.journalId,
        createdById: payload.userId,
        templateId: templateId,
      },
    })

    if (generatedAttachmentId) {
      await this.#_prisma.attachment.update({
        where: {
          id: generatedAttachmentId,
        },
        data: {
          documentId: createdDocument.id,
        },
      })
    }

    if (payload.attachments && payload.attachments.length > 0) {
      await this.#_prisma.attachment.updateMany({
        where: {
          id: {
            in: payload.attachments,
          },
        },
        data: {
          documentId: createdDocument.id,
        },
      })
    }

    await this.convertDocxToPdfForDocument(createdDocument.id, payload.userId)

    // Log document creation
    await this.#_auditLogService.logAction(
      'Document',
      createdDocument.id,
      AuditAction.CREATE,
      payload.userId,
      {
        newValues: {
          title: createdDocument.title,
          documentNumber: createdDocument.documentNumber,
          status: createdDocument.status,
          documentTypeId: createdDocument.documentTypeId,
          journalId: createdDocument.journalId,
        },
      },
    )
  }

  private async generateDocumentFromTemplate(
    template: any,
    tags: Record<string, any>,
    userId: string,
  ): Promise<string> {
    try {
      // Extract the file path from the URL
      const templateFileUrl = template.templateFile.fileUrl
      const templateFileName = templateFileUrl.replace(
        'https://cdn.nordicuniversity.org/docflow-files/',
        '',
      )

      // Download template file from MinIO
      const templateBuffer = await this.#_minio.getFile(templateFileName)

      // Generate document from template with tags
      const generatedDocBuffer =
        DocumentGeneratorUtil.generateDocumentFromTemplate(templateBuffer, tags)

      // Upload generated document to MinIO with sanitized filename
      const sanitizedFileName = this.#_minio.sanitizeFileName(
        template.templateFile.fileName,
      )
      const generatedFileName = `generated/${Date.now()}-${sanitizedFileName}`
      await this.#_minio.putFile(
        generatedFileName,
        generatedDocBuffer,
        template.templateFile.mimeType,
      )

      const generatedFileUrl = `https://cdn.nordicuniversity.org/docflow-files/${generatedFileName}`

      // Create attachment for generated document
      const generatedAttachment = await this.#_prisma.attachment.create({
        data: {
          fileName: template.templateFile.fileName,
          fileUrl: generatedFileUrl,
          fileSize: generatedDocBuffer.length,
          mimeType: template.templateFile.mimeType,
          uploadedById: userId,
          isAutoGenerated: false,
        },
      })

      this.logger.log('Document generated from template:', generatedFileUrl)
      return generatedAttachment.id
    } catch (error) {
      this.logger.error('Error generating document from template:', error)
      throw new Error(
        `Failed to generate document from template: ${error.message}`,
      )
    }
  }

  private async convertDocxToPdfForDocument(
    documentId: string,
    userId: string,
  ): Promise<void> {
    try {
      const docxAttachments = await this.#_prisma.attachment.findMany({
        where: {
          documentId: documentId,
          mimeType: {
            in: [
              'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
              'application/msword',
            ],
          },
          deletedAt: null,
        },
      })

      if (docxAttachments.length === 0) {
        this.logger.log('No DOCX attachments found for document:', documentId)
        return
      }

      // Get document to check for existing XFDF (for edge cases)
      const document = await this.#_prisma.document.findFirst({
        where: {
          id: documentId,
          deletedAt: null,
        },
        select: {
          xfdfUrl: true,
        },
      })

      // Process the first DOCX attachment
      const docxAttachment = docxAttachments[0]
      this.logger.log('Converting DOCX to PDF:', docxAttachment.fileName)

      // Extract the file path from the URL
      const fileUrl = docxAttachment.fileUrl
      const fileName = fileUrl.replace(
        'https://cdn.nordicuniversity.org/docflow-files/',
        '',
      )

      // Get the DOCX file from MinIO
      const docxBuffer = await this.#_minio.getFile(fileName)

      // Convert DOCX to PDF
      const { pdfBuffer, fileName: pdfFileName } =
        await PdfConverterUtil.convertDocxToPdf(
          docxBuffer,
          docxAttachment.fileName,
        )

      let finalPdfBuffer = pdfBuffer
      let finalPdfFileName = pdfFileName

      // If XFDF exists, merge it with the new PDF (for edge cases or re-conversions)
      if (document?.xfdfUrl) {
        this.logger.log('XFDF found during initial conversion, merging with PDF')
        const xfdfBuffer = Buffer.from(document.xfdfUrl, 'utf-8')

        const { pdfBuffer: mergedPdfBuffer, fileName: mergedFileName } =
          await PdfConverterUtil.mergeXfdfToPdf(
            pdfBuffer,
            xfdfBuffer,
            pdfFileName,
          )

        finalPdfBuffer = mergedPdfBuffer
        finalPdfFileName = mergedFileName
        this.logger.log('XFDF merged successfully with PDF')
      }

      // Upload PDF to MinIO with sanitized filename
      const sanitizedPdfFileName =
        this.#_minio.sanitizeFileName(finalPdfFileName)
      const uploadedPdfFileName = `attachments/${Date.now()}-${sanitizedPdfFileName}`
      await this.#_minio.putFile(
        uploadedPdfFileName,
        finalPdfBuffer,
        'application/pdf',
      )

      const pdfUrl = `https://cdn.nordicuniversity.org/docflow-files/${uploadedPdfFileName}`

      // Create attachment for PDF (store original filename for display)
      await this.#_prisma.attachment.create({
        data: {
          fileName: finalPdfFileName, // Keep original name for display
          fileUrl: pdfUrl,
          fileSize: finalPdfBuffer.length,
          mimeType: 'application/pdf',
          documentId: documentId,
          uploadedById: userId,
          isAutoGenerated: true,
        },
      })

      // Update document with PDF URL
      await this.#_prisma.document.update({
        where: {
          id: documentId,
        },
        data: {
          pdfUrl: pdfUrl,
        },
      })

      this.logger.log('PDF conversion completed successfully:', finalPdfFileName)
    } catch (error) {
      this.logger.error('Error converting DOCX to PDF:', error)
      // Don't throw error to prevent document creation from failing
      // Just log the error and continue
    }
  }

  async documentUpdate(payload: DocumentUpdateRequest): Promise<void> {
    const existingDocument = await this.#_prisma.document.findFirst({
      where: {
        id: payload.id,
        deletedAt: null,
      },
    })

    if (!existingDocument) {
      throw new NotFoundException('Document not found')
    }

    if (
      payload.documentNumber &&
      payload.documentNumber !== existingDocument.documentNumber
    ) {
      const documentWithSameNumber = await this.#_prisma.document.findFirst({
        where: {
          documentNumber: payload.documentNumber,
          deletedAt: null,
          id: { not: payload.id },
        },
      })

      if (documentWithSameNumber) {
        throw new ConflictException('Document number must be unique')
      }
    }

    if (payload.documentTypeId) {
      const documentType = await this.#_prisma.documentType.findFirst({
        where: {
          id: payload.documentTypeId,
          deletedAt: null,
        },
      })

      if (!documentType) {
        throw new NotFoundException('Document type not found')
      }
    }

    if (payload.journalId) {
      const journal = await this.#_prisma.journal.findFirst({
        where: {
          id: payload.journalId,
          deletedAt: null,
        },
      })

      if (!journal) {
        throw new NotFoundException('Journal not found')
      }
    }

    await this.#_prisma.document.update({
      where: {
        id: payload.id,
      },
      data: {
        title: payload.title,
        description: payload.description,
        status: (payload.status as DocumentStatus) ?? DocumentStatus.PENDING,
        documentTypeId: payload.documentTypeId,
        journalId: payload.journalId,
        updatedAt: new Date(),
      },
    })

    // Log document update
    const changes: Record<string, any> = {}
    if (payload.title && payload.title !== existingDocument.title) {
      changes.title = { old: existingDocument.title, new: payload.title }
    }
    if (
      payload.description &&
      payload.description !== existingDocument.description
    ) {
      changes.description = {
        old: existingDocument.description,
        new: payload.description,
      }
    }
    if (payload.status && payload.status !== existingDocument.status) {
      changes.status = { old: existingDocument.status, new: payload.status }
    }

    if (Object.keys(changes).length > 0) {
      await this.#_auditLogService.logAction(
        'Document',
        payload.id,
        AuditAction.UPDATE,
        payload.userId,
        {
          changes,
          oldValues: {
            title: existingDocument.title,
            description: existingDocument.description,
            status: existingDocument.status,
          },
          newValues: {
            title: payload.title || existingDocument.title,
            description: payload.description || existingDocument.description,
            status: payload.status || existingDocument.status,
          },
        },
      )
    }
  }

  async documentDelete(payload: DocumentDeleteRequest): Promise<void> {
    const isAdmin =
      payload.roleName === ROLE_NAMES.ADMIN ||
      payload.roleName === ROLE_NAMES.SUPER_ADMIN

    const existingDocument = await this.#_prisma.document.findFirst({
      where: {
        id: payload.id,
        ...(!isAdmin && payload.userId && { createdById: payload.userId }),
        deletedAt: null,
      },
    })

    if (!existingDocument) {
      throw new NotFoundException('Document not found')
    }

    await this.#_prisma.document.update({
      where: {
        id: payload.id,
      },
      data: {
        deletedAt: new Date(),
        updatedAt: new Date(),
      },
    })

    // Log document deletion
    await this.#_auditLogService.logAction(
      'Document',
      payload.id,
      AuditAction.DELETE,
      payload.userId,
      {
        oldValues: {
          title: existingDocument.title,
          documentNumber: existingDocument.documentNumber,
          status: existingDocument.status,
        },
      },
    )
  }

  async documentGetPdfUrl(
    documentId: string,
  ): Promise<{ pdfUrl: string | null; xfdfUrl: string | null }> {
    const document = await this.#_prisma.document.findFirst({
      where: {
        id: documentId,
        deletedAt: null,
      },
      select: {
        pdfUrl: true,
        xfdfUrl: true,
      },
    })

    if (!document) {
      throw new NotFoundException('Document not found')
    }

    return {
      pdfUrl: document.pdfUrl,
      xfdfUrl: document.xfdfUrl,
    }
  }

  async documentUpdateXfdfUrl(
    documentId: string,
    xfdfContent: string,
    userId?: string,
  ): Promise<void> {
    const document = await this.#_prisma.document.findFirst({
      where: {
        id: documentId,
        deletedAt: null,
      },
    })

    if (!document) {
      throw new NotFoundException('Document not found')
    }

    if (!document.pdfUrl) {
      throw new NotFoundException('PDF URL not found for this document')
    }

    // Check permissions: document creator and Super Admin can always edit
    let userWorkflowStep = null
    if (userId) {
      const isCreator = document.createdById === userId
      const user = await this.#_prisma.user.findFirst({
        where: { id: userId, deletedAt: null },
        select: { role: { select: { name: true } } },
      })
      const isSuperAdmin = user?.role?.name === ROLE_NAMES.SUPER_ADMIN

      // If not creator and not super admin, verify workflow permission
      if (!isCreator && !isSuperAdmin) {
        await this.#_workflowPermissionService.verifyXfdfEditPermission(
          userId,
          documentId,
        )
      }

      // Find the user's active workflow step (if exists)
      const workflow = await this.#_prisma.workflow.findFirst({
        where: {
          documentId,
          status: 'ACTIVE',
          deletedAt: null,
        },
        include: {
          workflowSteps: {
            where: {
              assignedToUserId: userId,
              isCreator: false,
              deletedAt: null,
            },
          },
        },
      })

      if (workflow) {
        const allowedStatuses =
          workflow.type === 'CONSECUTIVE'
            ? ['IN_PROGRESS']
            : ['IN_PROGRESS', 'NOT_STARTED']

        userWorkflowStep = workflow.workflowSteps.find((step) =>
          allowedStatuses.includes(step.status),
        )
      }
    }

    try {
      // Extract file paths from URLs
      const pdfFileName = document.pdfUrl.replace(
        'https://cdn.nordicuniversity.org/docflow-files/',
        '',
      )

      // Download original PDF from MinIO
      const pdfBuffer = await this.#_minio.getFile(pdfFileName)
      this.logger.log('Original PDF downloaded from MinIO')

      // Convert XFDF content to buffer
      const xfdfBuffer = Buffer.from(xfdfContent, 'utf-8')
      this.logger.log('XFDF content converted to buffer')

      // Extract original PDF filename
      const originalPdfFileName = pdfFileName.split('/').pop() || 'document.pdf'

      // Merge XFDF annotations into PDF
      const { pdfBuffer: mergedPdfBuffer, fileName: mergedFileName } =
        await PdfConverterUtil.mergeXfdfToPdf(
          pdfBuffer,
          xfdfBuffer,
          originalPdfFileName,
        )
      this.logger.log('XFDF merged into PDF successfully')

      // Versiya aniqlash
      const versionCount = await this.#_prisma.attachment.count({
        where: {
          documentId,
          mimeType: 'application/pdf',
          isAutoGenerated: true,
          deletedAt: null,
        },
      })
      const version = versionCount + 1

      // Tozalangan nom + versiya
      const cleanMergedName = mergedFileName
        .replace(/^\d+-/g, '')
        .replace(/^(merged-)+/g, '')
        .replace(/\s*\(v\d+\)/g, '')
      const ext = cleanMergedName.substring(cleanMergedName.lastIndexOf('.'))
      const nameWithoutExt = cleanMergedName.substring(
        0,
        cleanMergedName.lastIndexOf('.'),
      )
      const versionedName = `${nameWithoutExt} (v${version})${ext}`

      let sanitizedMergedFileName = this.#_minio.sanitizeFileName(versionedName)
      if (sanitizedMergedFileName.length > 100) {
        const extPart = sanitizedMergedFileName.substring(
          sanitizedMergedFileName.lastIndexOf('.'),
        )
        sanitizedMergedFileName =
          sanitizedMergedFileName.substring(0, 100 - extPart.length) + extPart
      }
      const uploadedPdfFileName = `attachments/${Date.now()}-${sanitizedMergedFileName}`
      await this.#_minio.putFile(
        uploadedPdfFileName,
        mergedPdfBuffer,
        'application/pdf',
      )

      const mergedPdfUrl = `https://cdn.nordicuniversity.org/docflow-files/${uploadedPdfFileName}`
      this.logger.log('Merged PDF uploaded to MinIO:', mergedPdfUrl)

      // Create attachment for merged PDF
      let displayFileName = versionedName
      if (displayFileName.length > 255) {
        const ext = displayFileName.substring(displayFileName.lastIndexOf('.'))
        displayFileName = displayFileName.substring(0, 255 - ext.length) + ext
      }
      await this.#_prisma.attachment.create({
        data: {
          fileName: displayFileName,
          fileUrl: mergedPdfUrl,
          fileSize: mergedPdfBuffer.length,
          mimeType: 'application/pdf',
          documentId: documentId,
          uploadedById: userId || document.createdById,
          isAutoGenerated: true,
        },
      })

      // Update document with XFDF content and new PDF URL
      await this.#_prisma.document.update({
        where: {
          id: documentId,
        },
        data: {
          xfdfUrl: xfdfContent,
          pdfUrl: mergedPdfUrl,
          updatedAt: new Date(),
        },
      })

      this.logger.log('Document updated with XFDF content and merged PDF URL')

      // Record XFDF submission in workflow step action if user has an active workflow step
      if (userWorkflowStep && userId) {
        this.logger.log(userWorkflowStep)
        await this.#_prisma.workflowStepAction.create({
          data: {
            workflowStepId: userWorkflowStep.id,
            actionType: 'COMMENTED',
            performedByUserId: userId,
            comment: 'XFDF annotations submitted',
            metadata: {
              xfdfSubmitted: true,
              xfdfSubmittedAt: new Date().toISOString(),
              actionType: userWorkflowStep.actionType,
            },
          },
        })
        this.logger.log(
          `XFDF submission recorded for user ${userId} on workflow step ${userWorkflowStep.id}`,
        )
      }
      this.logger.log('Nooooooooooooooooooooooooo')
    } catch (error) {
      this.logger.error('Error updating XFDF URL and merging PDF:', error)
      throw new Error(`Failed to update XFDF and merge PDF: ${error.message}`)
    }
  }

  async documentPublicVerification(documentId: string): Promise<any> {
    const document = await this.#_prisma.document.findFirst({
      where: {
        id: documentId,
        deletedAt: null,
      },
      select: {
        id: true,
        title: true,
        description: true,
        documentNumber: true,
        status: true,
        // priority: true, // NOTE: priority field does not exist in Document model
        createdAt: true,
        documentType: {
          select: {
            id: true,
            name: true,
          },
        },
        createdBy: {
          select: {
            id: true,
            fullname: true,
            username: true,
          },
        },
        workflow: {
          where: {
            deletedAt: null,
          },
          select: {
            id: true,
            status: true,
            type: true,
            currentStepOrder: true,
            createdAt: true,
            updatedAt: true,
            workflowSteps: {
              where: {
                deletedAt: null,
              },
              orderBy: {
                order: 'asc',
              },
              select: {
                id: true,
                order: true,
                status: true,
                actionType: true,
                startedAt: true,
                completedAt: true,
                isRejected: true,
                rejectionReason: true,
                assignedToUser: {
                  select: {
                    id: true,
                    fullname: true,
                    username: true,
                  },
                },
                actions: {
                  where: {
                    deletedAt: null,
                  },
                  orderBy: {
                    createdAt: 'desc',
                  },
                  select: {
                    id: true,
                    actionType: true,
                    comment: true,
                    createdAt: true,
                    performedBy: {
                      select: {
                        id: true,
                        fullname: true,
                        username: true,
                      },
                    },
                  },
                },
              },
            },
          },
        },
      },
    })

    if (!document) {
      throw new NotFoundException('Document not found')
    }

    return {
      id: document.id,
      title: document.title,
      description: document.description,
      documentNumber: document.documentNumber,
      status: document.status,
      documentType: document.documentType,
      createdBy: document.createdBy,
      createdAt: document.createdAt.toISOString(),
      workflow: document.workflow[0]
        ? {
            id: document.workflow[0].id,
            status: document.workflow[0].status,
            type: document.workflow[0].type,
            currentStepOrder: document.workflow[0].currentStepOrder,
            steps: document.workflow[0].workflowSteps.map((step) => ({
              id: step.id,
              order: step.order,
              status: step.status,
              actionType: step.actionType,
              assignedToUser: step.assignedToUser,
              startedAt: step.startedAt?.toISOString(),
              completedAt: step.completedAt?.toISOString(),
              isRejected: step.isRejected,
              rejectionReason: step.rejectionReason,
              actions: step.actions.map((action) => ({
                id: action.id,
                actionType: action.actionType,
                comment: action.comment,
                performedBy: action.performedBy,
                createdAt: action.createdAt.toISOString(),
              })),
            })),
            createdAt: document.workflow[0].createdAt.toISOString(),
            updatedAt: document.workflow[0].updatedAt.toISOString(),
          }
        : null,
    }
  }

  /**
   * Download accepted workflow document with watermark removal
   * @param documentId - Document ID to download
   * @param userId - Optional user ID for permission checks
   * @returns Object with PDF buffer and filename
   */
  async documentDownloadAccepted(
    documentId: string,
    userId?: string,
  ): Promise<{ pdfBuffer: Buffer; fileName: string }> {
    // Find document with workflow information
    const document = await this.#_prisma.document.findFirst({
      where: {
        id: documentId,
        deletedAt: null,
      },
      select: {
        id: true,
        title: true,
        status: true,
        pdfUrl: true,
        createdById: true,
        workflow: {
          where: {
            deletedAt: null,
          },
          select: {
            id: true,
            status: true,
            workflowSteps: {
              where: {
                deletedAt: null,
              },
              select: {
                id: true,
                assignedToUserId: true,
              },
            },
          },
        },
      },
    })

    if (!document) {
      throw new NotFoundException('Document not found')
    }

    // Check if document has a workflow
    if (!document.workflow || document.workflow.length === 0) {
      throw new BadRequestException(
        'Document does not have an associated workflow',
      )
    }

    // Check if workflow is completed
    const workflow = document.workflow[0]
    this.logger.log('DEBUG download:', {
      workflowId: workflow.id,
      workflowStatus: workflow.status,
      expected: WorkflowStatus.COMPLETED,
      isEqual: workflow.status === WorkflowStatus.COMPLETED,
    })
    if (workflow.status !== WorkflowStatus.COMPLETED) {
      throw new ForbiddenException(
        'Document workflow is not completed. Only approved documents can be downloaded.',
      )
    }

    // Check if document status is APPROVED
    if (document.status !== DocumentStatus.APPROVED) {
      throw new ForbiddenException(
        'Document is not approved. Only approved documents can be downloaded.',
      )
    }

    // Optional: Verify user has permission to download
    // (creator or someone who was assigned in the workflow)
    if (userId) {
      const isCreator = document.createdById === userId
      const wasAssigned = workflow.workflowSteps.some(
        (step) => step.assignedToUserId === userId,
      )

      if (!isCreator && !wasAssigned) {
        throw new ForbiddenException(
          'You do not have permission to download this document',
        )
      }
    }

    // Check if PDF URL exists
    if (!document.pdfUrl) {
      throw new NotFoundException('PDF file not found for this document')
    }

    try {
      // Extract file path from URL
      const pdfFileName = document.pdfUrl.replace(
        'https://cdn.nordicuniversity.org/docflow-files/',
        '',
      )

      // Download PDF from MinIO
      const pdfBuffer = await this.#_minio.getFile(pdfFileName)
      this.logger.log('PDF downloaded from MinIO for watermark removal')

      // Remove watermark from PDF
      const result = await removeWatermark(pdfBuffer)
      this.logger.log(
        `Watermark removal completed: ${result.watermarksRemoved} watermark(s) removed`,
      )

      // Extract filename for response
      const fileName = pdfFileName.split('/').pop() || 'document.pdf'

      return {
        pdfBuffer: result.cleanPdfBuffer,
        fileName: fileName,
      }
    } catch (error) {
      this.logger.error('Error downloading document with watermark removal:', error)
      throw new Error(
        `Failed to download document: ${(error as Error).message}`,
      )
    }
  }

  /**
   * Create a blank office document (docx/xlsx/pptx), upload to MinIO,
   * create attachment + document record, return Collabora editor URL
   */
  async documentCreateWithOffice(payload: {
    title: string
    description?: string
    documentTypeId: string
    journalId: string
    fileType?: 'docx' | 'xlsx' | 'pptx'
    userId: string
  }): Promise<any> {
    const fileType = payload.fileType || 'docx'

    // Validate document type and journal
    const documentType = await this.#_prisma.documentType.findFirst({
      where: { id: payload.documentTypeId, deletedAt: null },
    })
    if (!documentType) throw new NotFoundException('Hujjat turi topilmadi')

    const journal = await this.#_prisma.journal.findFirst({
      where: { id: payload.journalId, deletedAt: null },
    })
    if (!journal) throw new NotFoundException('Jurnal topilmadi')

    // Create minimal blank file
    const blankFiles: Record<string, Buffer> = {
      docx: this.createBlankDocx(),
      xlsx: this.createBlankXlsx(),
      pptx: this.createBlankPptx(),
    }

    const buffer = blankFiles[fileType]
    const mimeTypes: Record<string, string> = {
      docx: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
      xlsx: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
      pptx: 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    }

    const fileName = `${payload.title
      .replace(/[^a-zA-Z0-9\s-]/g, '')
      .trim()
      .replace(/\s+/g, '-')}.${fileType}`

    // Upload to MinIO
    const uploadedFileName = await this.#_minio.uploadFile(
      {
        buffer,
        originalname: fileName,
        mimetype: mimeTypes[fileType],
        size: buffer.length,
      } as any,
      'documents/',
    )

    const fileUrl = `https://cdn.nordicuniversity.org/docflow-files/${uploadedFileName}`

    // Create attachment record
    const attachment = await this.#_prisma.attachment.create({
      data: {
        fileName,
        fileUrl,
        fileSize: buffer.length,
        mimeType: mimeTypes[fileType],
        uploadedById: payload.userId,
        isAutoGenerated: true,
      },
    })

    // Generate document number
    const documentNumber = await DocumentNumberGenerator.generate(
      this.#_prisma,
      payload.journalId,
    )

    // Create document
    const document = await this.#_prisma.document.create({
      data: {
        title: payload.title,
        description: payload.description,
        documentNumber,
        status: DocumentStatus.DRAFT,
        documentTypeId: payload.documentTypeId,
        journalId: payload.journalId,
        createdById: payload.userId,
        pdfUrl: fileUrl,
      },
    })

    // Link attachment to document
    await this.#_prisma.attachment.update({
      where: { id: attachment.id },
      data: { documentId: document.id },
    })

    // Construct Collabora editor URL
    const wopiSrc = encodeURIComponent(
      `${process.env.WOPI_HOST_URL || 'https://api.docverse.uz'}/api/v1/wopi/files/${attachment.id}`,
    )
    const collaboraUrl = `https://office.docverse.uz/browser/dist/cool.html?WOPISrc=${wopiSrc}`

    return {
      document: {
        id: document.id,
        title: document.title,
        documentNumber: document.documentNumber,
        status: document.status,
      },
      attachment: {
        id: attachment.id,
        fileName: attachment.fileName,
        fileUrl: attachment.fileUrl,
      },
      collaboraUrl,
      wopiSrc: decodeURIComponent(wopiSrc),
      fileType,
    }
  }

  // Minimal valid DOCX (empty document)
  private createBlankDocx(): Buffer {
    const PizZip = require('pizzip')
    const Docxtemplater = require('docxtemplater')
    const zip = new PizZip()
    // Minimal OOXML structure
    zip.file(
      '[Content_Types].xml',
      '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/></Types>',
    )
    zip.file(
      '_rels/.rels',
      '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>',
    )
    zip.file(
      'word/document.xml',
      '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body><w:p><w:r><w:t></w:t></w:r></w:p></w:body></w:document>',
    )
    zip.file(
      'word/_rels/document.xml.rels',
      '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"></Relationships>',
    )
    return zip.generate({ type: 'nodebuffer' })
  }

  // Minimal valid XLSX
  private createBlankXlsx(): Buffer {
    const PizZip = require('pizzip')
    const zip = new PizZip()
    zip.file(
      '[Content_Types].xml',
      '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/></Types>',
    )
    zip.file(
      '_rels/.rels',
      '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>',
    )
    zip.file(
      'xl/workbook.xml',
      '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Sheet1" sheetId="1" r:id="rId1"/></sheets></workbook>',
    )
    zip.file(
      'xl/_rels/workbook.xml.rels',
      '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/></Relationships>',
    )
    zip.file(
      'xl/worksheets/sheet1.xml',
      '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData/></worksheet>',
    )
    return zip.generate({ type: 'nodebuffer' })
  }

  // Minimal valid PPTX
  private createBlankPptx(): Buffer {
    const PizZip = require('pizzip')
    const zip = new PizZip()
    zip.file(
      '[Content_Types].xml',
      '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/ppt/presentation.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.presentation.main+xml"/><Override PartName="/ppt/slides/slide1.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.slide+xml"/></Types>',
    )
    zip.file(
      '_rels/.rels',
      '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="ppt/presentation.xml"/></Relationships>',
    )
    zip.file(
      'ppt/presentation.xml',
      '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><p:presentation xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><p:sldIdLst><p:sldId id="256" r:id="rId2"/></p:sldIdLst></p:presentation>',
    )
    zip.file(
      'ppt/_rels/presentation.xml.rels',
      '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slide" Target="slides/slide1.xml"/></Relationships>',
    )
    zip.file(
      'ppt/slides/slide1.xml',
      '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><p:sld xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main"><p:cSld><p:spTree><p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr><p:grpSpPr/></p:spTree></p:cSld></p:sld>',
    )
    return zip.generate({ type: 'nodebuffer' })
  }
}
