/**
 * Document history / timeline service.
 *
 * document.service.ts'dan ajratildi — 295 qator self-contained logika.
 * Hujjatning to'liq tarixini (fayl versiyalari, workflow bosqichlari,
 * audit log, timeline) yaratadi.
 */

import {
  Injectable,
  Logger,
  NotFoundException,
  ForbiddenException,
} from '@nestjs/common'
import { PrismaService } from '@prisma'
import { isAdmin } from '@common/helpers'
import { translateActionTypeToUzbek } from '@common'
import {
  getWorkflowStepActionTitle,
  getAuditActionTitle,
} from '@common/utils/document-labels.util'
import { DocumentHistoryResponse, TimelineEntry } from './document.types'

@Injectable()
export class DocumentHistoryService {
  private readonly logger = new Logger(DocumentHistoryService.name)

  constructor(private readonly prisma: PrismaService) {}

  async getHistory(payload: {
    id: string
    userId: string
    roleName?: string
  }): Promise<DocumentHistoryResponse> {
    const document = await this.prisma.document.findFirst({
      where: { id: payload.id, deletedAt: null },
      include: {
        documentType: { select: { id: true, name: true } },
        journal: { select: { id: true, name: true, prefix: true } },
        createdBy: {
          select: { id: true, fullname: true, username: true, avatarUrl: true },
        },
        updatedBy: { select: { id: true, fullname: true, username: true } },
      },
    })

    if (!document) {
      throw new NotFoundException('Hujjat topilmadi')
    }

    // Permission check
    const admin = isAdmin(payload.roleName)
    if (!admin && document.createdById !== payload.userId) {
      const hasAccess = await this.prisma.workflowStep.findFirst({
        where: {
          assignedToUserId: payload.userId,
          workflow: { documentId: payload.id, deletedAt: null },
          deletedAt: null,
        },
      })
      if (!hasAccess) {
        throw new ForbiddenException(
          "Bu hujjat tarixini ko'rish huquqingiz yo'q",
        )
      }
    }

    // 1. Barcha fayl versiyalari
    const allAttachments = await this.prisma.attachment.findMany({
      where: { documentId: payload.id, deletedAt: null },
      orderBy: { createdAt: 'asc' },
      select: {
        id: true,
        fileName: true,
        fileUrl: true,
        fileSize: true,
        mimeType: true,
        isAutoGenerated: true,
        createdAt: true,
        uploadedBy: {
          select: { id: true, fullname: true, username: true, avatarUrl: true },
        },
      },
    })

    const fileVersions: Record<string, typeof allAttachments> = {}
    for (const att of allAttachments) {
      if (!fileVersions[att.mimeType]) fileVersions[att.mimeType] = []
      fileVersions[att.mimeType].push(att)
    }

    // 2. Workflow va barcha bosqichlar + harakatlari
    const workflows = await this.prisma.workflow.findMany({
      where: { documentId: payload.id, deletedAt: null },
      include: {
        workflowSteps: {
          where: { deletedAt: null },
          orderBy: { order: 'asc' },
          include: {
            assignedToUser: {
              select: {
                id: true,
                fullname: true,
                username: true,
                avatarUrl: true,
              },
            },
            actions: {
              orderBy: { createdAt: 'asc' },
              include: {
                performedBy: {
                  select: {
                    id: true,
                    fullname: true,
                    username: true,
                    avatarUrl: true,
                  },
                },
              },
            },
            attachments: {
              include: {
                attachment: {
                  select: {
                    id: true,
                    fileName: true,
                    fileUrl: true,
                    mimeType: true,
                  },
                },
                uploadedBy: { select: { id: true, fullname: true } },
              },
            },
          },
        },
      },
    })

    // 3. Audit log
    const auditLogs = await this.prisma.auditLog.findMany({
      where: {
        entity: 'Document',
        entityId: payload.id,
        deletedAt: null,
      },
      orderBy: { performedAt: 'desc' },
      include: {
        performedBy: {
          select: { id: true, fullname: true, username: true, avatarUrl: true },
        },
      },
    })

    // 4. Timeline
    const timeline: TimelineEntry[] = []

    // Hujjat yaratildi
    timeline.push({
      type: 'DOCUMENT_CREATED',
      timestamp: document.createdAt,
      actor: document.createdBy,
      title: 'Hujjat yaratildi',
      description: `"${document.title}" hujjati yaratildi`,
      meta: { documentNumber: document.documentNumber, status: 'DRAFT' },
    })

    // Fayl versiyalari
    for (const att of allAttachments) {
      timeline.push({
        type: 'FILE_UPLOADED',
        timestamp: att.createdAt,
        actor: att.uploadedBy,
        title: att.isAutoGenerated
          ? 'Avtomatik PDF yaratildi'
          : 'Fayl yuklandi',
        description: att.fileName,
        meta: {
          attachmentId: att.id,
          fileName: att.fileName,
          fileUrl: att.fileUrl,
          mimeType: att.mimeType,
          fileSize: att.fileSize,
        },
      })
    }

    // Workflow steplar va actionlar
    for (const wf of workflows) {
      timeline.push({
        type: 'WORKFLOW_STARTED',
        timestamp: wf.createdAt,
        actor: document.createdBy,
        title: 'Ish jarayoni boshlandi',
        description: `${wf.type === 'CONSECUTIVE' ? 'Ketma-ket' : 'Parallel'} ish jarayoni`,
        meta: { workflowId: wf.id, type: wf.type, status: wf.status },
      })

      for (const step of wf.workflowSteps) {
        if (step.isCreator) continue

        if (step.startedAt) {
          timeline.push({
            type: 'STEP_STARTED',
            timestamp: step.startedAt,
            actor: step.assignedToUser,
            title: `${step.order}-bosqich boshlandi: ${translateActionTypeToUzbek(step.actionType)}`,
            description: `${step.assignedToUser?.fullname || ''} ga tayinlandi`,
            meta: {
              stepId: step.id,
              order: step.order,
              actionType: step.actionType,
              dueDate: step.dueDate,
            },
          })
        }

        for (const action of step.actions) {
          timeline.push({
            type: `STEP_${action.actionType}`,
            timestamp: action.createdAt,
            actor: action.performedBy,
            title: getWorkflowStepActionTitle(
              action.actionType,
              step.order,
              step.actionType,
            ),
            description: action.comment || '',
            meta: {
              stepId: step.id,
              actionType: action.actionType,
              comment: action.comment,
            },
          })
        }

        if (step.isRejected && step.rejectedAt) {
          timeline.push({
            type: 'STEP_REJECTED',
            timestamp: step.rejectedAt,
            actor: step.assignedToUser,
            title: `${step.order}-bosqich rad etildi`,
            description: step.rejectionReason || '',
            meta: { stepId: step.id, reason: step.rejectionReason },
          })
        }

        if (step.completedAt && !step.isRejected) {
          timeline.push({
            type: 'STEP_COMPLETED',
            timestamp: step.completedAt,
            actor: step.assignedToUser,
            title: `${step.order}-bosqich yakunlandi: ${translateActionTypeToUzbek(step.actionType)}`,
            description: `${step.assignedToUser?.fullname || ''} muvaffaqiyatli bajardi`,
            meta: {
              stepId: step.id,
              order: step.order,
              actionType: step.actionType,
            },
          })
        }
      }
    }

    // Audit log yozuvlari
    for (const log of auditLogs) {
      timeline.push({
        type: `AUDIT_${log.action}`,
        timestamp: log.performedAt,
        actor: log.performedBy,
        title: getAuditActionTitle(log.action),
        description: '',
        meta: {
          changes: log.changes,
          oldValues: log.oldValues,
          newValues: log.newValues,
          ipAddress: log.ipAddress,
        },
      })
    }

    // Vaqt bo'yicha tartiblash
    timeline.sort(
      (a, b) =>
        new Date(a.timestamp!).getTime() - new Date(b.timestamp!).getTime(),
    )

    return {
      document: {
        id: document.id,
        title: document.title,
        documentNumber: document.documentNumber,
        status: document.status,
        documentType: document.documentType,
        journal: document.journal,
        createdBy: document.createdBy,
        updatedBy: document.updatedBy,
        createdAt: document.createdAt,
        updatedAt: document.updatedAt,
      },
      summary: {
        totalVersions: allAttachments.length,
        totalSteps: workflows.reduce(
          (sum, wf) =>
            sum + wf.workflowSteps.filter((s) => !s.isCreator).length,
          0,
        ),
        totalActions: workflows.reduce(
          (sum, wf) =>
            sum +
            wf.workflowSteps.reduce((s, step) => s + step.actions.length, 0),
          0,
        ),
        currentStatus: document.status,
        workflowsCount: workflows.length,
      },
      fileVersions,
      workflows,
      auditLogs,
      timeline,
    }
  }
}
