/**
 * Document module — shared type definitions.
 *
 * document.service.ts, document-history.service.ts, document-public.service.ts
 * barcha sub-service'lar shu fayldan import qiladi.
 */

export interface DocumentAttachmentSelect {
  id: string
  fileName: string
  fileUrl: string
  fileSize: number
  mimeType: string
  isAutoGenerated: boolean
  createdAt: Date
  updatedAt: Date
}

export interface TimelineEntry {
  type: string
  timestamp: Date | null
  actor: Record<string, unknown> | null
  title: string
  description: string
  meta: Record<string, unknown>
}

export interface DocumentHistoryResponse {
  document: Record<string, unknown>
  summary: Record<string, unknown>
  fileVersions: Record<string, unknown[]>
  workflows: unknown[]
  auditLogs: unknown[]
  timeline: TimelineEntry[]
}

export interface DocumentPublicVerificationResponse {
  id: string
  title: string
  description: string | null
  documentNumber: string | null
  status: string
  documentType: { id: string; name: string } | null
  createdBy: { id: string; fullname: string; username: string }
  createdAt: string
  workflow: Record<string, unknown> | null
}

export interface DocumentBlankResponse {
  document: {
    id: string
    title: string
    documentNumber: string | null
    status: string
  }
  attachment: {
    id: string
    fileName: string
    fileUrl: string
  }
  collaboraUrl: string
  wopiSrc: string
  fileType: string
}

export interface DocumentTemplateWithFile {
  id: string
  name: string
  description: string | null
  templateFileId: string
  documentTypeId: string
  requiredTags: unknown
  isActive: boolean
  isPublic: boolean
  templateFile: {
    id: string
    fileName: string
    fileUrl: string
    fileSize: number
    mimeType: string
    [key: string]: unknown
  }
  [key: string]: unknown
}
